create table if not exists public.leaderboard_scores (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(trim(player_name)) between 1 and 18),
  distance integer not null check (distance >= 0 and distance <= 999999),
  coins integer not null default 0 check (coins >= 0 and coins <= 9999),
  final_score integer not null default 0 check (final_score >= 0 and final_score <= 999999),
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.leaderboard_scores
  add column if not exists coins integer not null default 0 check (coins >= 0 and coins <= 9999);

alter table public.leaderboard_scores
  add column if not exists final_score integer not null default 0 check (final_score >= 0 and final_score <= 999999);

update public.leaderboard_scores
set final_score = distance
where final_score = 0 and distance > 0;

drop index if exists leaderboard_scores_distance_idx;

create index if not exists leaderboard_scores_final_score_idx
  on public.leaderboard_scores (final_score desc, created_at desc);

alter table public.leaderboard_scores enable row level security;

drop policy if exists "Public can read leaderboard scores" on public.leaderboard_scores;
create policy "Public can read leaderboard scores"
on public.leaderboard_scores
for select
to anon
using (true);

drop policy if exists "Public can insert leaderboard scores" on public.leaderboard_scores;
create policy "Public can insert leaderboard scores"
on public.leaderboard_scores
for insert
to anon
with check (
  char_length(trim(player_name)) between 1 and 18
  and distance >= 0
  and distance <= 999999
  and coins >= 0
  and coins <= 9999
  and final_score >= 0
  and final_score <= 999999
);

create table if not exists public.guestbook_messages (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(trim(player_name)) between 1 and 18),
  message text not null check (char_length(trim(message)) between 1 and 120),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists guestbook_messages_created_at_idx
  on public.guestbook_messages (created_at desc);

alter table public.guestbook_messages enable row level security;

drop policy if exists "Public can read guestbook messages" on public.guestbook_messages;
create policy "Public can read guestbook messages"
on public.guestbook_messages
for select
to anon
using (true);

drop policy if exists "Public can insert guestbook messages" on public.guestbook_messages;
create policy "Public can insert guestbook messages"
on public.guestbook_messages
for insert
to anon
with check (
  char_length(trim(player_name)) between 1 and 18
  and char_length(trim(message)) between 1 and 120
);
